//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeTau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangTau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChangTau()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int Id { get; set; }
        public string MaChuyenDi { get; set; }
        public string TenChuyenDi { get; set; }
        public Nullable<int> DiemDi { get; set; }
        public Nullable<int> DiemDen { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
        public Nullable<System.DateTime> NgayDen { get; set; }
        public Nullable<int> SoLuongChang { get; set; }
        public Nullable<int> GiaVe { get; set; }
        public Nullable<bool> DaDat { get; set; }
        public Nullable<bool> IsLocked { get; set; }
    
        public virtual GaDen GaDen { get; set; }
        public virtual GaDi GaDi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
