//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeTau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int Id { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public Nullable<int> ChangId { get; set; }
        public string DaDat { get; set; }
    
        public virtual ChangTau ChangTau { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
