//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeTau.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BanVeTauEntities : DbContext
    {
        public BanVeTauEntities()
            : base("name=BanVeTauEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChangTau> ChangTaus { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<GaDen> GaDens { get; set; }
        public virtual DbSet<GaDi> GaDis { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int ThemDonHang(Nullable<int> khachHangID, Nullable<int> changID, string daDat)
        {
            var khachHangIDParameter = khachHangID.HasValue ?
                new ObjectParameter("KhachHangID", khachHangID) :
                new ObjectParameter("KhachHangID", typeof(int));
    
            var changIDParameter = changID.HasValue ?
                new ObjectParameter("ChangID", changID) :
                new ObjectParameter("ChangID", typeof(int));
    
            var daDatParameter = daDat != null ?
                new ObjectParameter("DaDat", daDat) :
                new ObjectParameter("DaDat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemDonHang", khachHangIDParameter, changIDParameter, daDatParameter);
        }
    }
}
