//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanVeTau.admin {
    
    
    public partial class quan_ly_chang_tau {
        
        /// <summary>
        /// quanlychangtau control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BanVeTau.admin.Control.quanlychangtau quanlychangtau;
    }
}
